### ISSUE TITLE
Session Headers and Raw strings

### ISSUE THREAD

**Issue by NovaDrak0n** [ading2210/passmark-scraper#1]
When I went to try to run your program on my machine, I was faced with 2 errors.
1. On lines 146, 153, and 162 you have "[^0123456789\.]" as a string and I get the Syantex Warning:

SyntaxWarning: invalid escape sequence '\.'

By changing this to a raw string "[^0123456789\.]" => r"[^0123456789\.]"
I was able to fix this issue.

2. When I tried to search I found that I was not receiving any data. After some debug print statements, I found I was getting a 403 Status Code from the www.cpubenchmark.net. To fix this I updated the headers dictionary in the scrape method to include a User-Agent. This allowed me to access the site and scrape data.

I will be making a pull request shortly to make these updates.

**Comment by ading2210** [comment]
I just merged your PR which should fix the issue.
